[build]

# Build command for the site
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/CognitiveHorizonsDev/obsidian-zola.git __site && __site/run.sh"
base = ""
publish = "public"

[build.environment]
# Button text on the landing page
LANDING_BUTTON = "Explore Cognitive Horizons"
# Description shown on the landing page
LANDING_DESCRIPTION = "Dive deep into the realm of knowledge and perspectives."
# The Markdown page linked to the landing page button
LANDING_PAGE = "home"
# Title shown on the landing page
LANDING_TITLE = "Cognitive Horizons"
# Python version (if required by any custom scripts)
PYTHON_VERSION = "3.8"
# Repository URL for the site (unchanged)
REPO_URL = "https://github.com/CognitiveHorizonsDev/obsidian-zola"
# Site title shown in the navbar
SITE_TITLE = "Cognitive Horizons"
# Title shown in the browser tab (if blank, SITE_TITLE is used)
SITE_TITLE_TAB = "Cognitive Horizons"
# URL where the site will be hosted
SITE_URL = "https://cognitivehorizons.netlify.app"
# Site timezone
TIMEZONE = "America/New_York"
# Zola version used for building
ZOLA_VERSION = "0.15.2"
# Sorting method for notes on the sidebar ("date" or "title")
SORT_BY = "title"
# Google Analytics Measurement ID (leave blank if not using)
GANALYTICS = ""
# Enable slugified URLs (leave blank to disable)
SLUGIFY = "y"
# Enable knowledge graph on the home page
HOME_GRAPH = "y"
# Enable knowledge graph on all pages
PAGE_GRAPH = "y"
# Collapse sidebar sections by default (leave blank to disable)
SIDEBAR_COLLAPSED = ""
# Additional footer content
FOOTER = "Crafted with curiosity at Cognitive Horizons"
# Root section name for organizing content
ROOT_SECTION_NAME = "main"
# Options for the knowledge graph visualization (vis.js)
GRAPH_OPTIONS = """
        {
        	nodes: {
        		shape: "dot",
        		color: isDark() ? "#8c8e91" : "#dee2e6",
        		font: {
        			face: "Inter",
        			color: isDark() ? "#c9cdd1" : "#616469",
        			strokeColor: isDark() ? "#c9cdd1" : "#616469",
        		},
        		scaling: {
        			label: {
        				enabled: true,
        			},
        		},
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 0.8,
        		smooth: {
        			type: "continuous",
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	physics: {
        		solver: "repulsion",
        	},
        }
        """
